using System.Collections.Generic;

namespace Cameca.CustomAnalysis.Utilities;

public static class PeriodicTableLayoutConsts
{
	public const int ColumnsCount = 18;
	public const int RowsCount = 10;
	public const int FreeSpaceHeight = 32;

	public static IReadOnlyDictionary<Element, (int row, int column)> GridPositions = new Dictionary<Element, (int row, int column)>
    {
        { Element.H, (0, 0) },
        { Element.He, (0, 17) },
        { Element.Li, (1, 0) },
        { Element.Be, (1, 1) },
        { Element.B, (1, 12) },
        { Element.C, (1, 13) },
        { Element.N, (1, 14) },
        { Element.O, (1, 15) },
        { Element.F, (1, 16) },
        { Element.Ne, (1, 17) },
        { Element.Na, (2, 0) },
        { Element.Mg, (2, 1) },
        { Element.Al, (2, 12) },
        { Element.Si, (2, 13) },
        { Element.P, (2, 14) },
        { Element.S, (2, 15) },
        { Element.Cl, (2, 16) },
        { Element.Ar, (2, 17) },
        { Element.K, (3, 0) },
        { Element.Ca, (3, 1) },
        { Element.Sc, (3, 2) },
        { Element.Ti, (3, 3) },
        { Element.V, (3, 4) },
        { Element.Cr, (3, 5) },
        { Element.Mn, (3, 6) },
        { Element.Fe, (3, 7) },
        { Element.Co, (3, 8) },
        { Element.Ni, (3, 9) },
        { Element.Cu, (3, 10) },
        { Element.Zn, (3, 11) },
        { Element.Ga, (3, 12) },
        { Element.Ge, (3, 13) },
        { Element.As, (3, 14) },
        { Element.Se, (3, 15) },
        { Element.Br, (3, 16) },
        { Element.Kr, (3, 17) },
        { Element.Rb, (4, 0) },
        { Element.Sr, (4, 1) },
        { Element.Y, (4, 2) },
        { Element.Zr, (4, 3) },
        { Element.Nb, (4, 4) },
        { Element.Mo, (4, 5) },
        { Element.Tc, (4, 6) },
        { Element.Ru, (4, 7) },
        { Element.Rh, (4, 8) },
        { Element.Pd, (4, 9) },
        { Element.Ag, (4, 10) },
        { Element.Cd, (4, 11) },
        { Element.In, (4, 12) },
        { Element.Sn, (4, 13) },
        { Element.Sb, (4, 14) },
        { Element.Te, (4, 15) },
        { Element.I, (4, 16) },
        { Element.Xe, (4, 17) },
        { Element.Cs, (5, 0) },
        { Element.Ba, (5, 1) },
        { Element.La, (5, 2) },
        { Element.Ce, (8, 3) },
        { Element.Pr, (8, 4) },
        { Element.Nd, (8, 5) },
        { Element.Pm, (8, 6) },
        { Element.Sm, (8, 7) },
        { Element.Eu, (8, 8) },
        { Element.Gd, (8, 9) },
        { Element.Tb, (8, 10) },
        { Element.Dy, (8, 11) },
        { Element.Ho, (8, 12) },
        { Element.Er, (8, 13) },
        { Element.Tm, (8, 14) },
        { Element.Yb, (8, 15) },
        { Element.Lu, (8, 16) },
        { Element.Hf, (5, 3) },
        { Element.Ta, (5, 4) },
        { Element.W, (5, 5) },
        { Element.Re, (5, 6) },
        { Element.Os, (5, 7) },
        { Element.Ir, (5, 8) },
        { Element.Pt, (5, 9) },
        { Element.Au, (5, 10) },
        { Element.Hg, (5, 11) },
        { Element.Tl, (5, 12) },
        { Element.Pb, (5, 13) },
        { Element.Bi, (5, 14) },
        { Element.Po, (5, 15) },
        { Element.At, (5, 16) },
        { Element.Rn, (5, 17) },
        { Element.Fr, (6, 0) },
        { Element.Ra, (6, 1) },
        { Element.Ac, (6, 2) },
        { Element.Th, (9, 3) },
        { Element.Pa, (9, 4) },
        { Element.U, (9, 5) },
        { Element.Np, (9, 6) },
        { Element.Pu, (9, 7) },
        { Element.Am, (9, 8) },
        { Element.Cm, (9, 9) },
        { Element.Bk, (9, 10) },
        { Element.Cf, (9, 11) },
        { Element.Es, (9, 12) },
        { Element.Fm, (9, 13) },
        { Element.Md, (9, 14) },
        { Element.No, (9, 15) },
        { Element.Lr, (9, 16) },
        { Element.Rf, (6, 3) },
        { Element.Db, (6, 4) },
        { Element.Sg, (6, 5) },
        { Element.Bh, (6, 6) },
        { Element.Hs, (6, 7) },
        { Element.Mt, (6, 8) },
        { Element.Ds, (6, 9) },
        { Element.Rg, (6, 10) },
        { Element.Cn, (6, 11) },
        { Element.Nh, (6, 12) },
        { Element.Fl, (6, 13) },
        { Element.Mc, (6, 14) },
        { Element.Lv, (6, 15) },
        { Element.Ts, (6, 16) },
        { Element.Og, (6, 17) },
    };
}
